services:
  cache:
    image: redis:latest
    container_name: nestjs-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - nestjs-network
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword

  redisinsight:
    image: redis/redisinsight:latest
    container_name: nestjs-redisinsight
    restart: unless-stopped
    ports:
      - '5540:5540'
    volumes:
      - redisinsight-data:/db
    networks:
      - nestjs-network

volumes:
  mysql_data:
    driver: local
  redisinsight-data:
    driver: local

networks:
  nestjs-network:
    driver: bridge
