services:
  cache:
    image: redis:latest
    container_name: nestjs-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - nestjs-network
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  mysql_data:
    driver: local

networks:
  nestjs-network:
    driver: bridge
